### ISSUE TITLE
Add a visual monitor.

### ISSUE THREAD

**Issue by mldk-tech** [Gizra-Shoov/Nhl#1]
https://www.nhl.com/

**Comment by DavidKohav** [comment]
![ct8uyopu8ae01rtnsh](https://cloud.githubusercontent.com/assets/5812423/12777204/f9631686-ca63-11e5-9bcc-ad27654ada7e.jpg)

**Comment by DavidKohav** [comment]
![ct8uyopu8ae01rtnsh943 531](https://cloud.githubusercontent.com/assets/5812423/12777473/e3951410-ca65-11e5-9dda-38de19d4dd51.jpg)

**Comment by DavidKohav** [comment]
![ct8uyopu8ae01rt140](https://cloud.githubusercontent.com/assets/5812423/12783755/f203f3f6-ca8b-11e5-899b-2c0681335963.jpg)

**Comment by mldk-tech** [comment]
https://app.shoov.io/#/screenshots/22198

**Comment by mldk-tech** [comment]
http://gfycat.com/VerifiableShabbyAurochs

**Comment by mldk-tech** [comment]
@kazabooboo

**Comment by DavidKohav** [comment]
@david@gizra.com

**Comment by kazabooboo** [comment]
Thanks!
